export const mockOffers = [
  // ---- OUTGOING OFFERS YOU MADE ----
  {
    id: 201,
    item: 'Mountain Bike',        // Target listing
    offerType: 'money',
    offeredFor: '$80',            // Money amount
    status: 'Pending',
    image: 'https://picsum.photos/seed/bike/400/300',
  },
  {
    id: 202,
    item: 'Bluetooth Headphones',
    offerType: 'swap',
    offeredItem: {
      id: 101,
      title: 'Kindle Paperwhite',
      category: 'Books',
      condition: 'Good',
      description: '6-inch glare-free screen with backlight.',
      image: 'https://picsum.photos/seed/kindle/400/300',
    },
    offeredFor: 'Kindle Paperwhite',
    status: 'Accepted',
    image: 'https://picsum.photos/seed/headphones/400/300',
  },
  {
    id: 203,
    item: 'Gaming Laptop',
    offerType: 'both',
    offeredItem: {
      id: 102,
      title: 'Old MacBook',
      category: 'Computers',
      condition: 'Used',
      description: '2015 model with 8GB RAM, still runs fine.',
      image: 'https://picsum.photos/seed/macbook/400/300',
    },
    offeredFor: 'Old MacBook + $100',
    status: 'Rejected',
    image: 'https://picsum.photos/seed/laptop/400/300',
  },

  // ---- OFFERS RECEIVED ON YOUR LISTINGS ----
  {
    id: 301,
    item: 'Mountain Bike',
    offerType: 'money',
    offeredFor: '$120',
    status: 'Pending',
    image: 'https://picsum.photos/seed/bikeoffer/400/300',
  },
  {
    id: 302,
    item: 'Mountain Bike',
    offerType: 'swap',
    offeredItem: {
      id: 103,
      title: 'Canon EOS 250D',
      category: 'Electronics',
      condition: 'Like New',
      description: 'Compact DSLR camera with 24MP sensor and 18–55mm lens.',
      image: 'https://picsum.photos/seed/camera/400/300',
    },
    offeredFor: 'Canon EOS 250D',
    status: 'Pending',
    image: 'https://picsum.photos/seed/camera/400/300',
  },
  {
    id: 303,
    item: 'Bluetooth Headphones',
    offerType: 'both',
    offeredItem: {
      id: 104,
      title: 'Smart Watch',
      category: 'Wearables',
      condition: 'Good',
      description: 'Water-resistant, Bluetooth enabled fitness tracking watch.',
      image: 'https://picsum.photos/seed/watch/400/300',
    },
    offeredFor: 'Smart Watch + $50',
    status: 'Pending',
    image: 'https://picsum.photos/seed/watch/400/300',
  },
  {
    id: 304,
    item: 'Mountain Bike',
    offerType: 'both',
    offeredItem: {
      id: 105,
      title: 'GoPro Hero 10',
      category: 'Cameras',
      condition: 'Like New',
      description: 'Action camera with 5.3K video and waterproof housing.',
      image: 'https://picsum.photos/seed/gopro/400/300',
    },
    offeredFor: 'GoPro Hero 10 + $40',
    status: 'Accepted',
    image: 'https://picsum.photos/seed/gopro/400/300',
  },
  {
    id: 305,
    item: 'Bluetooth Headphones',
    offerType: 'swap',
    offeredItem: {
      id: 106,
      title: 'Used iPhone 11',
      category: 'Phones',
      condition: 'Fair',
      description: '64GB version, some scratches but fully functional.',
      image: 'https://picsum.photos/seed/iphone/400/300',
    },
    offeredFor: 'Used iPhone 11',
    status: 'Rejected',
    image: 'https://picsum.photos/seed/iphone/400/300',
  },
];
